---
  language: java
  jdk:
    - oraclejdk8
  cache:
    directories:
      - "~/.m2"
  before_install:
    - sudo apt-get install libaio1
  script: mvn verify
  before_deploy: cat travis/bintray_template.json | sed s/\$\{TRAVIS_TAG\}/${TRAVIS_TAG}/g > travis/release.json
  deploy:
    on:
      tags: true
    provider: bintray
    edge: true
    file: travis/release.json
    user:
      secure: NiC/w+eddXAfsnheXanAt1CaDyZD2E0+4hap6PDVOZyeKPBOFFHMLJ3BFDCZMNsTgO62O9KIMavVNCr1bjsiPcHVa7CULoOemYMcraDPWKA/6v0s2ps4t5gSJxRCCUZ0hVrPkozzOsYg/5IcbRZfmVSpfGeFWa4SPedh5TK93aYuaLuAuVjeqmX5SjKOcyjtu8azMwBedUUdRo2WtV1x9VRSUuHLrTVSVtxnPpVu8e2yANrmiyBIgw1fnFdYYk2WKao18/ucIuD0GLImm2SuZQBckTKXmEQateBRWcopHoYchQC8iDsceKzFOrHWC80XmrEE1qa9fFFH/cV7ZqZzd1hY+qRObwaXfxJTjApdFjcOYpHR1/HntlGpwa7vXAcHg6pt6ToU1FLXfcOh9EFZBvztTh+n4bWraZrYnVuOXVsZQdiN4wQ2rUkAvWSRz3Y5NHdP33Qzp9JkgWIDn8OjdxDbhUrh4x6Q3L8Kzh8KXsvVsowlpBgkm0Be5ymj85Mdsm+LoUIv3Mr946YbHXqJA70F9NcfvMlpgPPVEa+2gqJbguRnZYzQV3P4vxqj3wh8VsAIKvI5kN6RzSdEe9agHu7dsm8l1JrmZITBqqd07HvG7xCARBdJtAXs1+x9sGFDt80JwPSYXmXNQVqPuSLlBqCKsGZ/ysiRW3bg6DVaDks=
    key:
      secure: lGuYPsyJ4tYt5ma8OImPEGIgNeQWL7PwBpnyPHTIp+O3CBAPgz1oxHInc3r/ku6bmBSPKaCiOpazO6JHp7ux0kmbOnLkW7VRSnIzbFz2zyVioSl73+X1VuPDqVFI0ftq2AkkWwrQEJ6PgewcMZiGROIhU169+TdLArU9zNdK8csg6/XsHTwCBJfWMceQfRzQjC1SEcMHS9yGNxO8NuVBzb5bdptHexa8R9LA+XAqij9UwZQ6EudyGO6X7rAcKfXEVPBcwiAF6rxJXN/0vaE399Jno/B79IuSt5eDfbKZTMPTNAlLCsfl45Q/Q0eAHKVKYdWAJ9An0fKVuCh4HaVgGsCSTN9dXLY8k3y1HK+HnZ8vPLvahJw3AQY+SmIuKnfxS1DcbeshIjxS7+1o6tsRl3cY2iiu8KlzYO26ITr5AW/iR2SxxEUp4wSiWS1n8hMstPL+2AqT7CPVfP9Q5WZN0edogt8NJnHNlmtFONzIDdnYq/W0xsLiTyeEx5qLETTA5Dqja3iI2X9yCxnVTAFeZ2XWP4SnIHR9i/tMSynuTNQm9JvjrtrsDleF3HKfLhV73HSi2AjZD1YLgCCs9Td/EEgXocnfZwUuS49CS1HeDbuv7Ya21s9SgTrb0RSPv6D5uE51O0quh0rmzPk1cD18yn2um4zmDo+BaB0QN98y6X4=
  after_deploy: echo "Pending"
